// ===== Mock Data for Development =====
// Used when Clerk/PostgreSQL are not configured

import { InstrumentData, CourseCardData, LessonData, DashboardStats, TeacherStats, AdminStats } from "@/types";

export const INSTRUMENTS: InstrumentData[] = [
  {
    id: "piano",
    name: "Piano / Clavier",
    slug: "piano",
    description: "Apprenez le piano classique, jazz, pop et plus encore. Des fondamentaux aux techniques avancées.",
    icon: "🎹",
    color: "#6C3CE1",
    courseCount: 24,
  },
  {
    id: "guitar",
    name: "Guitare",
    slug: "guitare",
    description: "Guitare acoustique et électrique. Rock, blues, folk, classique et fingerpicking.",
    icon: "🎸",
    color: "#F59E0B",
    courseCount: 31,
  },
  {
    id: "bass",
    name: "Basse",
    slug: "basse",
    description: "Basse électrique et acoustique. Grooves, slap, walking bass et techniques modernes.",
    icon: "🎸",
    color: "#10B981",
    courseCount: 12,
  },
  {
    id: "drums",
    name: "Batterie / Percussions",
    slug: "batterie",
    description: "Batterie acoustique et électronique. Rythmes, rudiments, fills et coordination.",
    icon: "🥁",
    color: "#EF4444",
    courseCount: 18,
  },
  {
    id: "vocals",
    name: "Chant / Voix",
    slug: "chant",
    description: "Technique vocale, interprétation, placement de voix et styles variés.",
    icon: "🎤",
    color: "#EC4899",
    courseCount: 15,
  },
  {
    id: "violin",
    name: "Violon / Alto / Violoncelle",
    slug: "violon",
    description: "Instruments à cordes frottées. Classique, musique de chambre et styles modernes.",
    icon: "🎻",
    color: "#8B5CF6",
    courseCount: 9,
  },
  {
    id: "ukulele",
    name: "Ukulele",
    slug: "ukulele",
    description: "L'instrument fun par excellence. Accords, fingerpicking et chansons populaires.",
    icon: "🪕",
    color: "#06B6D4",
    courseCount: 8,
  },
  {
    id: "wind",
    name: "Instruments à vent",
    slug: "instruments-a-vent",
    description: "Saxophone, trompette, flûte et clarinette. Jazz, classique et musique contemporaine.",
    icon: "🎷",
    color: "#F97316",
    courseCount: 11,
  },
  {
    id: "theory",
    name: "Théorie Musicale",
    slug: "theorie-musicale",
    description: "Solfège, harmonie, analyse et composition. Les fondamentaux pour tout musicien.",
    icon: "📖",
    color: "#64748B",
    courseCount: 20,
  },
  {
    id: "production",
    name: "MAO / Production",
    slug: "mao-production",
    description: "Production musicale, mixage, mastering, DJing et création de beats.",
    icon: "🎧",
    color: "#A855F7",
    courseCount: 14,
  },
];

export const FEATURED_COURSES: CourseCardData[] = [
  {
    id: "1",
    title: "Piano : Les Fondamentaux",
    slug: "piano-les-fondamentaux",
    description: "Un parcours complet pour maîtriser les bases du piano. Posture, lecture de notes, accords et premiers morceaux.",
    thumbnailUrl: null,
    level: "BEGINNER",
    style: "CLASSICAL",
    duration: 480,
    lessonCount: 24,
    teacher: { firstName: "Marie", lastName: "Dupont", avatarUrl: null },
    instrument: { name: "Piano / Clavier", slug: "piano", color: "#6C3CE1" },
  },
  {
    id: "2",
    title: "Guitare Acoustique pour Débutants",
    slug: "guitare-acoustique-debutants",
    description: "Apprenez vos premiers accords, le strumming et jouez vos chansons préférées en quelques semaines.",
    thumbnailUrl: null,
    level: "BEGINNER",
    style: "POP",
    duration: 360,
    lessonCount: 18,
    teacher: { firstName: "Thomas", lastName: "Martin", avatarUrl: null },
    instrument: { name: "Guitare", slug: "guitare", color: "#F59E0B" },
  },
  {
    id: "3",
    title: "Blues Guitar Masterclass",
    slug: "blues-guitar-masterclass",
    description: "Plongez dans le blues : gammes pentatoniques, bends, vibrato et improvisation. De Robert Johnson à Stevie Ray Vaughan.",
    thumbnailUrl: null,
    level: "INTERMEDIATE",
    style: "BLUES",
    duration: 540,
    lessonCount: 27,
    teacher: { firstName: "Jean", lastName: "Lefebvre", avatarUrl: null },
    instrument: { name: "Guitare", slug: "guitare", color: "#F59E0B" },
  },
  {
    id: "4",
    title: "Jazz Piano Avancé",
    slug: "jazz-piano-avance",
    description: "Harmonie jazz, voicings, improvisation et standards. Pour pianistes intermédiaires à avancés.",
    thumbnailUrl: null,
    level: "ADVANCED",
    style: "JAZZ",
    duration: 720,
    lessonCount: 36,
    teacher: { firstName: "Sophie", lastName: "Bernard", avatarUrl: null },
    instrument: { name: "Piano / Clavier", slug: "piano", color: "#6C3CE1" },
  },
  {
    id: "5",
    title: "Batterie Rock : Les Essentiels",
    slug: "batterie-rock-essentiels",
    description: "Apprenez les rythmes rock fondamentaux, les fills et la coordination main-pied.",
    thumbnailUrl: null,
    level: "BEGINNER",
    style: "ROCK",
    duration: 300,
    lessonCount: 15,
    teacher: { firstName: "Lucas", lastName: "Moreau", avatarUrl: null },
    instrument: { name: "Batterie / Percussions", slug: "batterie", color: "#EF4444" },
  },
  {
    id: "6",
    title: "Technique Vocale : Libérez votre Voix",
    slug: "technique-vocale-liberez-voix",
    description: "Respiration, placement, tessiture et interprétation. Un parcours complet pour développer votre voix.",
    thumbnailUrl: null,
    level: "BEGINNER",
    style: "POP",
    duration: 420,
    lessonCount: 21,
    teacher: { firstName: "Camille", lastName: "Rousseau", avatarUrl: null },
    instrument: { name: "Chant / Voix", slug: "chant", color: "#EC4899" },
  },
];

export const DEMO_LESSONS: LessonData[] = [
  {
    id: "l1",
    title: "Introduction au Piano",
    description: "Découvrez l'instrument, sa mécanique et comment bien vous installer.",
    videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    duration: 600,
    sortOrder: 1,
    isFree: true,
    completed: true,
    watchedSeconds: 600,
    resources: [
      { id: "r1", title: "Guide de posture (PDF)", type: "PDF", fileUrl: "#" },
    ],
  },
  {
    id: "l2",
    title: "Les Notes sur le Clavier",
    description: "Apprenez à identifier toutes les notes sur le clavier : do, ré, mi, fa, sol, la, si.",
    videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    duration: 720,
    sortOrder: 2,
    isFree: true,
    completed: true,
    watchedSeconds: 720,
    resources: [
      { id: "r2", title: "Schéma du clavier", type: "PDF", fileUrl: "#" },
    ],
  },
  {
    id: "l3",
    title: "Premiers Accords Majeurs",
    description: "Découvrez les accords de Do, Fa et Sol majeurs et comment les enchaîner.",
    videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    duration: 900,
    sortOrder: 3,
    isFree: false,
    completed: false,
    watchedSeconds: 450,
    resources: [
      { id: "r3", title: "Partitions des accords", type: "PDF", fileUrl: "#" },
      { id: "r4", title: "Playback accompagnement", type: "AUDIO", fileUrl: "#" },
    ],
  },
  {
    id: "l4",
    title: "La Main Gauche : Basses et Arpèges",
    description: "Développez l'indépendance de votre main gauche avec des patterns de basse.",
    videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    duration: 840,
    sortOrder: 4,
    isFree: false,
    completed: false,
    watchedSeconds: 0,
    resources: [
      { id: "r5", title: "Exercices main gauche", type: "PDF", fileUrl: "#" },
    ],
  },
  {
    id: "l5",
    title: "Votre Premier Morceau : Lettre à Élise",
    description: "Apprenez le début de la célèbre Lettre à Élise de Beethoven pas à pas.",
    videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    duration: 1200,
    sortOrder: 5,
    isFree: false,
    completed: false,
    watchedSeconds: 0,
    resources: [
      { id: "r6", title: "Partition - Lettre à Élise", type: "PDF", fileUrl: "#" },
      { id: "r7", title: "Playback lent", type: "AUDIO", fileUrl: "#" },
      { id: "r8", title: "Tablature simplifiée", type: "TAB", fileUrl: "#" },
    ],
  },
];

export const LEARNER_STATS: DashboardStats = {
  totalCourses: 3,
  completedLessons: 14,
  totalWatchTime: 1260,
  currentStreak: 5,
};

export const TEACHER_STATS: TeacherStats = {
  totalStudents: 342,
  totalCourses: 8,
  totalViews: 12450,
  totalRevenue: 4280,
};

export const ADMIN_STATS: AdminStats = {
  totalUsers: 2847,
  totalLearners: 2534,
  totalTeachers: 48,
  activeSubscriptions: 1832,
  totalCourses: 156,
  totalRevenue: 28450,
  retentionRate: 78.5,
};

export const MOCK_ENROLLED_COURSES: CourseCardData[] = [
  { ...FEATURED_COURSES[0], progress: 42, enrolled: true },
  { ...FEATURED_COURSES[2], progress: 15, enrolled: true },
  { ...FEATURED_COURSES[3], progress: 78, enrolled: true },
];

export const PRICING_PLANS = [
  {
    name: "Basic",
    price: 9.90,
    period: "mois",
    description: "Accès à tous les cours vidéo et outils de base",
    features: [
      "Accès illimité aux cours vidéo",
      "Progression automatique",
      "Partitions & tablatures PDF",
      "Métronome & tuner intégrés",
      "Communauté et forum",
      "Support par email",
    ],
    notIncluded: [
      "Masterclasses exclusives",
      "Cours live avec les profs",
      "Coaching 1-to-1",
      "Playbacks et accompagnements",
      "Certification de progression",
    ],
    cta: "Commencer avec Basic",
    popular: false,
  },
  {
    name: "VIP",
    price: 14.90,
    period: "mois",
    description: "L'expérience complète avec masterclasses et outils avancés",
    features: [
      "Tout ce qui est dans Basic",
      "Masterclasses exclusives",
      "Cours live avec les profs",
      "Coaching 1-to-1 (1h/mois)",
      "Playbacks et accompagnements",
      "Certification de progression",
      "Piano virtuel & drum machine",
      "Support prioritaire",
    ],
    notIncluded: [],
    cta: "Devenir VIP",
    popular: true,
  },
];
